# version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bonpreu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  etl:
    build: .
    container_name: bonpreu-etl
    depends_on:
      - db
    environment:
      MYSQL_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    volumes:
      - ./data:/app/data
      - ./wait-for-db.sh:/app/wait-for-db.sh
    command: ["bash", "/app/wait-for-db.sh", "db", "3306", "python", "etl/etl_main.py"]


volumes:
  db_data: